In [1]:
import pandas as pd
from main import *
from helper import *
from solution import *

In [2]:
# Data locations
datapath = "../../data/"
train_loc = datapath + "train.txt"
test_loc = datapath + "test.txt"

# Import data
train_df = load_data(train_loc)
test_df = load_data(test_loc)

In [3]:
print("Train dataset shape: ", train_df.shape)
print("Test dataset shape: ", test_df.shape)

Train dataset shape:  (1561, 257)
Test dataset shape:  (424, 257)


### Transform and Split Dataset Into Train and Test Sets

In [4]:
def get_X_y(df):
    observations_range = df[:].shape[0]

    label = []
    sys = []
    intense = []

    for i in range(observations_range):

        input_extract_features = df[:, 1:][i]
        sys_intense = extract_feature(input_extract_features)

        sys_temp = sys_intense[0]
        intense_temp = sys_intense[1]
        label_temp = df[:,0][i]

        sys.append(sys_temp)
        intense.append(intense_temp)
        label.append(label_temp)
        
        X = np.column_stack((sys, intense))
        y = np.array(label)

        # transform y labels
        y = np.where(y == 5, -1, 1)
        
    return X, y

In [5]:
X_train, y_train = get_X_y(train_df)
X_test, y_test = get_X_y(test_df)

In [6]:
X_train.shape

(1561, 2)

In [7]:
y_train.shape

(1561,)

In [8]:
y_train

array([-1,  1,  1, ...,  1,  1,  1])

### Build Perceptron Class

In [9]:
np.zeros(X_train.shape[1] + 1)

array([0., 0., 0.])

In [10]:
max_iter = 2
for _ in range(max_iter):
    print("1")

1
1


In [11]:
W = np.zeros(X_train.shape[1] + 1)

max_iter = 2
for _ in range(max_iter):
    print(W)
    for xi, target in zip(X_train, y_train):
        xi = np.insert(xi, 0, 1, axis=0)
        print("xi: ", xi, " | ", "target: ", target)
        print("Weights",W)

[0. 0. 0.]
xi:  [ 1.         -0.53372656 -0.11173828]  |  target:  -1
Weights [0. 0. 0.]
xi:  [ 1.         -0.1174375  -0.75391406]  |  target:  1
Weights [0. 0. 0.]
xi:  [ 1.         -0.16229688 -0.77228125]  |  target:  1
Weights [0. 0. 0.]
xi:  [ 1.         -0.0595     -0.76925781]  |  target:  1
Weights [0. 0. 0.]
xi:  [ 1.         -0.05090625 -0.7954375 ]  |  target:  1
Weights [0. 0. 0.]
xi:  [ 1.         -0.34746875 -0.71591406]  |  target:  1
Weights [0. 0. 0.]
xi:  [ 1.         -0.16164063 -0.70207031]  |  target:  1
Weights [0. 0. 0.]
xi:  [ 1.         -0.06861719 -0.74220703]  |  target:  1
Weights [0. 0. 0.]
xi:  [ 1.         -0.40299219 -0.56403516]  |  target:  -1
Weights [0. 0. 0.]
xi:  [ 1.         -0.02532813 -0.712375  ]  |  target:  1
Weights [0. 0. 0.]
xi:  [ 1.         -0.1210625  -0.63432031]  |  target:  1
Weights [0. 0. 0.]
xi:  [ 1.         -0.040875   -0.70267188]  |  target:  1
Weights [0. 0. 0.]
xi:  [ 1.         -0.04852344 -0.72720703]  |  target:  1
Weigh

In [25]:
class Perceptron(object):
    
    def __init__(self, max_iter):
        self.max_iter = max_iter

    def fit(self, X, y):
        """Train perceptron model on data (X,y).

        Args:
            X: An array of shape [n_samples, n_features].
            y: An array of shape [n_samples,]. Only contains 1 or -1.

        Returns:
            self: Returns an instance of self.
        """
        ### YOUR CODE HERE
        
        # Define the max iterations
        max_inter = self.max_iter

        # Initialize Weights
        self.W = np.zeros(X.shape[1] + 1)
        
        # Loop through the number of iterations
        for _ in range(max_iter):
            print(self.W)
            print("")
            
            # Loop through the dataset
            for xi, target in zip(X, y):

                # Insert 1 to match with Wo
                xi = np.insert(xi, 0, 1, axis=0)

                # Compute predictions 
                prediction = np.dot(xi, self.W)

                # Apply Sign function to predictions
                prediction_sign = np.where(prediction >= .00, 1, -1)

                print(xi, "--> Xi")
                print(self.W, "--> Weights") 
                print("Prediction: ", prediction, " prediction_sign: ", prediction_sign, " target: ", target)
                print("")
                
                # Update weights
                self.W += (target - prediction_sign) * xi
        
        ### END YOUR CODE
        
        return self
    
    def get_params(self):
        """Get parameters for this perceptron model.

        Returns:
            W: An array of shape [n_features,].
        """
        if self.W is None:
            print("Run fit first!")
            sys.exit(-1)
        return self.W

    def predict(self, X):
        """Predict class labels for samples in X.

        Args:
            X: An array of shape [n_samples, n_features].

        Returns:
            preds: An array of shape [n_samples,]. Only contains 1 or -1.
        """
        ### YOUR CODE HERE



        ### END YOUR CODE

    def score(self, X, y):
        """Returns the mean accuracy on the given test data and labels.

        Args:
            X: An array of shape [n_samples, n_features].
            y: An array of shape [n_samples,]. Only contains 1 or -1.

        Returns:
            score: An float. Mean accuracy of self.predict(X) wrt. y.
        """
        ### YOUR CODE HERE



        ### END YOUR CODE




def show_result(X, y, W):
    """Plot the linear model after training. 
       You can call show_features with 'save' being False for convenience.

    Args:
        X: An array of shape [n_samples, 2].
        y: An array of shape [n_samples,]. Only contains 1 or -1.
        W: An array of shape [n_features,].
    
    Returns:
        Do not return any arguments. Save the plot to 'result.*' and include it
        in your report.
    """
    ### YOUR CODE HERE



    ### END YOUR CODE



def test_perceptron(max_iter, X_train, y_train, X_test, y_test):

    # train perceptron
    model = Perceptron(max_iter)
    model.fit(X_train, y_train)
    train_acc = model.score(X_train, y_train)
    W = model.get_params()

    # test perceptron model
    test_acc = model.score(X_test, y_test)

    return W, train_acc, test_acc

In [26]:
X_train[0:3]

array([[-0.53372656, -0.11173828],
       [-0.1174375 , -0.75391406],
       [-0.16229688, -0.77228125]])

In [27]:
model = Perceptron(2)
model.fit(X_train[0:2], y_train[0:2])

[0. 0. 0.]

[ 1.         -0.53372656 -0.11173828] --> Xi
[0. 0. 0.] --> Weights
Prediction:  0.0  prediction_sign:  1  target:  -1

[ 1.         -0.1174375  -0.75391406] --> Xi
[-2.          1.06745312  0.22347656] --> Weights
Prediction:  -2.2938411494750977  prediction_sign:  -1  target:  1

[ 0.          0.83257812 -1.28435156]

[ 1.         -0.53372656 -0.11173828] --> Xi
[ 0.          0.83257812 -1.28435156] --> Weights
Prediction:  -0.3008578245544431  prediction_sign:  -1  target:  -1

[ 1.         -0.1174375  -0.75391406] --> Xi
[ 0.          0.83257812 -1.28435156] --> Weights
Prediction:  0.8705148106079101  prediction_sign:  1  target:  1

